blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/customskinloader
    about: Community chat for CustomSkinLoader users.
  - name: QQ Group
    url: https://jq.qq.com/?_wv=1027&k=vF16R5tg
    about: Chinese community chat for CustomSkinLoader users.
