name: 提交问题
description: 报告问题以帮助我们改进CustomSkinLoader
labels: [ bug ]
body:
  - type: textarea
    id: description
    attributes:
      label: 描述问题
      description: |
        简单的描述问题, 并提供类似图片、视频，以更好的报告错误(如果可以)
        ！注意：请不要在这里放日志文件或崩溃报告文件的内容
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: 复现步骤
      description: 请问你是如何触发这个问题的
      render: bash
    validations:
      required: true
  - type: input
    id: crash-report
    attributes:
      label: 在此处放入崩溃报告的链接 ( https://mclo.gs )
  - type: input
    id: latest-log
    attributes:
      label: 在此处放入latest.log的链接 ( https://mclo.gs )
  - type: input
    id: mod-version
    attributes:
      label: 模组版本
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft游戏版本
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: 操作系统
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: 在提交错误报告之前,有没有做到...
      options:
        - label: |
            先尝试搜索issues里面, 查看并确认打开或关闭的工单, 是否搜索不到
          required: true
        - label: |
            确认你的模组版本是最新的开发版本,且文件下载正确,没有出现类似forge下载了fabric版的这类基础问题
          required: true
