name: 提交问题
description: 报告问题以帮助我们改进CustomSkinLoader
labels: [ bug ]
title: "[Bug] "
body:
  - type: markdown
    attributes:
       value: |
        你好，这里是 `CustomSkinLoader`
        标注红色星号的为必填项
        以及，保持工单干净整洁，不要直接将日志内容粘贴到工单上，比如粘贴到描述内是不行的
  - type: textarea
    id: description
    attributes:
      label: 描述问题
      description: |
        简单的描述问题, 并提供类似图片、视频，以更好的报告错误(如果可以)
        ！注意：请不要在这里放日志文件或崩溃报告文件的内容
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: 复现步骤
      description: 请问你是如何触发这个问题的
      render: bash
      value:  |
       1. 
       2. 
       3. 
    validations:
      required: true
  - type: input
    id: crash-report
    attributes:
      label: 崩溃报告查看地址
      description: |
       在游戏目录下的 `crash-reports` 文件夹下,里面找最近的报告生成时间
       客户端若无崩溃则直接填写 `客户端无崩溃`
       [生成连接](https://mclo.gs)
      placeholder: "Ex: https://mclo.gs/xxxxxx"
  - type: input
    id: csl-log
    attributes:
      label: CustomSkinLoader.log 查看地址
      description: |
       文件路径:`<游戏路径>/CustomSkinLoader/CustomSkinLoader.log`.
       [生成连接](https://mclo.gs)
      placeholder: "Ex: https://mclo.gs/xxxxxx"
  - type: input
    id: latest-log
    attributes:
      label: latest.log 查看地址
      description: |
       文件路径:`<游戏路径>/logs/latest.log`.
       [生成连接](https://mclo.gs)
      placeholder: "Ex: https://mclo.gs/xxxxxx"
  - type: input
    id: forge-log
    attributes:
      label: "[仅Forge用户] debug.log (=>1.12.2) 或者 fml-client-latest.log (=<1.12.2) 查看地址"
      description: |
       文件路径:`<游戏路径>/logs/debug.log` 或者 `<游戏路径>/logs/fml-client-latest.log`.
       若没有使用 `Forge` 加载器的，可以不填写
       [生成连接](https://mclo.gs)
      placeholder: "Ex: https://mclo.gs/xxxxxx"
  - type: input
    id: mod-version
    attributes:
      label: 模组版本
      placeholder: "Ex: 14.16"
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft游戏版本
      placeholder: "Ex: 1.19.4"
    validations:
      required: true
  - type: input
    id: mc-launcher-version
    attributes:
      label: Minecraft启动器 名称 及 版本
      placeholder: "Ex: HMCL v3.5.4.232"
      description: |
        若不知道游戏版本 可以只填写游戏启动器的名称
    validations:
      required: true
  - type: dropdown
    id: loader-type
    attributes:
      label: 模组加载器
      options:
        - Quilt
        - Fabric
        - Forge
        - 不使用加载器
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: 操作系统
      options:
        - Windows
        - Linux
        - macOS
        - 其他操作系统
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: 在提交错误报告之前,有没有做到...
      options:
        - label: |
            先尝试搜索issues里面, 查看并确认打开或关闭的工单, 是否搜索不到
          required: true
        - label: |
            确认你的模组版本是最新的开发版本,且文件下载正确,没有出现类似forge下载了fabric版的这类基础问题
          required: true
        - label: |
            这个问题是在最新的mod版本触发(若不是最新的请先升级mod)
          required: true
