
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.ow2.asm:asm-debug-all:5.2"
    }
}

import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes
import org.objectweb.asm.tree.AbstractInsnNode
import org.objectweb.asm.tree.ClassNode
import org.objectweb.asm.tree.InsnList
import org.objectweb.asm.tree.MethodInsnNode
import org.objectweb.asm.tree.MethodNode

import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream


configurations {
    patchClass
}

void patch(Object dependency, Closure<Boolean> fileFilter, List<Map<String, Closure>> filters) {
    project.dependencies {
        patchClass dependency
    }

    project.afterEvaluate {
        project.configurations.patchClass.findAll { fileFilter.call(it) }.each { File jarFile ->
            def outputJar = file("${project.gradle.gradleUserHomeDir}/caches/customskinloader/libs/${jarFile.name}")
            outputJar.parentFile.mkdirs()

            new ZipOutputStream(new FileOutputStream(outputJar)).withCloseable { zos ->
                new ZipFile(jarFile).withCloseable { zf ->
                    zf.entries().each { ZipEntry entry ->
                        if (entry.name.startsWith('META-INF/') && (entry.name.endsWith('.RSA') || entry.name.endsWith('.SF'))) {
                            return
                        }

                        def applicableFilters = filters.findAll { it.classFilter.call(entry.name) }
                        if (applicableFilters) {
                            def cn = new ClassNode()
                            new ClassReader(zf.getInputStream(entry).bytes).accept(cn, 0)

                            applicableFilters.each { filter ->
                                cn.methods.findAll { filter.methodFilter.call(it) }.each { method ->
                                     method.instructions.toArray().findAll { filter.nodeFilter.call(it) }.each { filter.methodPatcher.call(method.instructions, it) }
                                }
                            }

                            def cw = new ClassWriter(ClassWriter.COMPUTE_MAXS)
                            cn.accept(cw)
                            zos.putNextEntry(new ZipEntry(entry.name))
                            zos.write(cw.toByteArray())
                            zos.closeEntry()
                        } else {
                            zos.putNextEntry(new ZipEntry(entry.name))
                            zos.write(zf.getInputStream(entry).bytes)
                            zos.closeEntry()
                        }
                    }
                }
            }

            project.dependencies {
                compile files(outputJar)
                compile dependency
            }
        }
    }
}

// Mercury assumes that all classes containing '$' are inner classes and ignores classes that contain '$' natively.
void patchMercury() {
    this.patch(
        "org.cadixdev:mercury:0.1.0",
        { File f ->
            f.name == "mercury-0.1.0.jar"
        },
        [
            [
                classFilter: { String name ->
                    name == "org/cadixdev/mercury/remapper/RemapperVisitor.class"
                },
                methodFilter: { MethodNode mn ->
                    mn.name == "remapType" && mn.desc == "(Lorg/eclipse/jdt/core/dom/SimpleName;Lorg/eclipse/jdt/core/dom/ITypeBinding;)V"
                },
                nodeFilter: { AbstractInsnNode node ->
                    node.opcode == Opcodes.ASTORE && node.var == 4
                },
                methodPatcher: { InsnList list, AbstractInsnNode node ->
                    list.insertBefore(node, new MethodInsnNode(Opcodes.INVOKESTATIC, "customskinloader/gradle/util/RemapUtil", "fixClassName", "(Ljava/lang/String;)Ljava/lang/String;", false))
                }
            ]
        ]
    )
}

void patchMixin() {
    // Mixin uses incorrect method for field descriptors to get the signature.
    this.patch(
        "org.spongepowered:mixin:0.8.5",
        { File f ->
            f.name == "mixin-0.8.5.jar"
        },
        [
            [
                classFilter: { String name ->
                    name == "org/spongepowered/tools/obfuscation/mirror/TypeHandleASM.class"
                },
                methodFilter: { MethodNode mn ->
                    mn.name == "findField" && mn.desc == "(Ljava/lang/String;Ljava/lang/String;Z)Lorg/spongepowered/tools/obfuscation/mirror/FieldHandle;"
                },
                nodeFilter: { AbstractInsnNode node ->
                    node.opcode == Opcodes.INVOKESTATIC && node.owner == "org/spongepowered/tools/obfuscation/mirror/TypeUtils" && node.name == "getJavaSignature" && node.desc == "(Ljava/lang/String;)Ljava/lang/String;"
                },
                methodPatcher: { InsnList list, AbstractInsnNode node ->
                    list.insertBefore(node, new MethodInsnNode(Opcodes.INVOKESTATIC, "org/objectweb/asm/Type", "getType", "(Ljava/lang/String;)Lorg/objectweb/asm/Type;", false))
                    list.set(node, new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "org/objectweb/asm/Type", "getClassName", "()Ljava/lang/String;", false))
                }
            ],
            [
                classFilter: { String name ->
                    name == "org/spongepowered/tools/obfuscation/mapping/common/MappingProvider.class"
                },
                methodFilter: { MethodNode mn ->
                    mn.name == "<init>" && mn.desc == "(Ljavax/annotation/processing/Messager;Ljavax/annotation/processing/Filer;)V"
                },
                nodeFilter: { AbstractInsnNode node ->
                    node.opcode == Opcodes.PUTFIELD && node.owner == "org/spongepowered/tools/obfuscation/mapping/common/MappingProvider" && node.desc == "Lcom/google/common/collect/BiMap;"
                },
                methodPatcher: { InsnList list, AbstractInsnNode node ->
                    list.insertBefore(node, new MethodInsnNode(Opcodes.INVOKESTATIC, "customskinloader/dummy/FakeBiMap", "create", "(Lcom/google/common/collect/BiMap;)Lcom/google/common/collect/BiMap;", false))
                }
            ]
        ]
    )
}

ext {
    patchMixin = this.&patchMixin
    patchMercury = this.&patchMercury
}
