name: Beta

on:
  push:
    branches:
      - 15-develop
  workflow_dispatch:

jobs:
  build-beta:
    name: Build Beta
    uses: ./.github/workflows/common.yml
    with:
      type: Beta
      publish: true
      prerelease-tag: Beta-Build
      prerelease-name: CustomSkinLoader Beta Build
      latest-json: latest-beta.json
      detail-json: detail-beta.json
      is-snapshot: true
    secrets: inherit
