name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [15-develop]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/build
        with:
          artifact-name: CustomSkinLoader-PR-${{ github.run_number }}
